<a href="https://colab.research.google.com/github/Devdeep-J-S/woc5.0-ml-weather-prediction-case-study-Devdeep/blob/main/WOC5.0-ML-Checkpoint-2/WOC5_0_ML_Checkpoint_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Reading the above CSV file in google colab using the pandasâ€™ library and converting it into data frames.

In [1]:
# data from drive 
import pandas as pd
path = 'https://raw.githubusercontent.com/Devdeep-J-S/woc5.0-ml-weather-prediction-case-study-Devdeep/main/WOC5.0-ML-Checkpoint-2/Youtube%20Influencer%20Analysis%20-%20Updated.csv'
df = pd.read_csv(path,sep=",", encoding='mac_roman')

In [2]:
# first 5 row print 
df.head()

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,...,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data
0,https://www.youtube.com/watch?v=_0fUOJ55gis,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,https://www.youtube.com/c/sriharick,srihari ck,Male,40200,7964284,00:30:41,"1,841.00",...,Yes,0,419,8/6/2022,1080,462,12.0,No,1,Akhil Teja
1,https://www.youtube.com/watch?v=_70MSLPRfZI,"231,969",Bhoom Baddhal Web Series,https://www.youtube.com/c/ChaibisketTelugu,Chai Bisket,Male,920000,137535681,00:14:24,864.00,...,Yes,1,189,6/15/2022,1080,251,12.0,Yes,2,Akhil Teja
2,https://www.youtube.com/watch?v=_8gfCdt3H00&t=87s,878,"Customer Psychology, Four Views Of Consumer De...",https://www.youtube.com/channel/UCcIUnCsBfONvb...,Virda Warsi,Female,458,72945,0:08:12,492.00,...,Yes,0,0,NaN,720,158,0.0,No,0,Syed safdar
3,https://www.youtube.com/watch?v=_CkFNJgKsFs,"9,965",Top countries with proven natural gas reserves,https://www.youtube.com/c/trtworld,TRT,NaN,1680000,541653219,0:01:06,66.00,...,Yes,0,77,9/22/2022,1080,46509,48.0,No,20,Syed safdar
4,https://www.youtube.com/watch?v=_GFkHA5EZdE,"39,780,561",73 Questions With Selena Gomez,Vogue - YouTube,Vogue,NaN,12100000,3600496171,0:07:40,460.00,...,Yes,0,28221,9/23/2022,1080,2872,113.0,No,1,Rahul Singh

2) How many values are missing for each column and try dropping or replacing NULL values using appropriate pandasâ€™ function.

In [ ]:
# how many values are missing 
# before 
print("Before dropping rows with missing values")
print(df.isna().sum())

# droping rows with null values 
# method -1 : df[df.isnull().any(axis=1)]
df.dropna(inplace=True)

#after 
print("After dropping rows with missing values")
print(df.isna().sum())

Video Link                               0
Video Views                              0
Video Title                              0
Channel URL                              0
Creator Name                             0
Creator Gender                           0
Total Channel Subcribers                 0
Total Chanel Views                       0
Duration of Video                        0
Duration in Seconds                      0
Date of Video Upload                     0
No of Likes                              0
Language of the Video                    0
Subtitle                                 0
Video Description                        0
Hashtags                                 0
No of Comments                           0
Date of the Last Comment                 0
Maximum Quality of the Video             0
No of Videos the Channel                 0
No of Playlist                           0
Premiered or Not                         0
Community Engagement (Posts per week)    0
Intern Who Collected the Data            0
dtype: int64
Video Link                               0
Video Views                              0
Video Title                              0
Channel URL                              0
Creator Name                             0
Creator Gender                           0
Total Channel Subcribers                 0
Total Chanel Views                       0
Duration of Video                        0
Duration in Seconds                      0
Date of Video Upload                     0
No of Likes                              0
Language of the Video                    0
Subtitle                                 0
Video Description                        0
Hashtags                                 0
No of Comments                           0
Date of the Last Comment                 0
Maximum Quality of the Video             0
No of Videos the Channel                 0
No of Playlist                           0
Premiered or Not                         0
Community Engagement (Posts per week)    0
Intern Who Collected the Data            0
dtype: int64

3) Drop the columns which are irrelevant features to feed into our model.

In [ ]:
# suppose duration of video is irrelevent feature 
df.drop(['Duration of Video'],axis=1,inplace=True)

In [ ]:
# # print in tabular form to see the change easily 
# from tabulate import tabulate
# print(tabulate(df, headers="keys", tablefmt="psql"))
df.head()

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration in Seconds,Date of Video Upload,...,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data
0,https://www.youtube.com/watch?v=_0fUOJ55gis,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,https://www.youtube.com/c/sriharick,srihari ck,Male,40200,7964284,"1,841.00",7/29/2022,...,Yes,0,419,8/6/2022,1080,462,12.0,No,1,Akhil Teja
1,https://www.youtube.com/watch?v=_70MSLPRfZI,"231,969",Bhoom Baddhal Web Series,https://www.youtube.com/c/ChaibisketTelugu,Chai Bisket,Male,920000,137535681,864.00,5/22/2022,...,Yes,1,189,6/15/2022,1080,251,12.0,Yes,2,Akhil Teja
5,https://www.youtube.com/watch?v=_HwPGXsklyY,"257,334",HERO - Baananchige Oduva Baara,https://www.youtube.com/c/RishabShettyFilms,Rishab Shetty Films,Male,382000,154898226,361.00,3/24/2021,...,Yes,1,387,4/24/2021,2160,94,14.0,No,0,Akhil Teja
10,https://www.youtube.com/watch?v=0BBROgyHlFE,"5,599,742",ROUNDER GLUTES: 5 Mistakes Keeping Your Butt Flat,https://www.youtube.com/c/JeremyEthier,Jeremy Ethier,Male,4690000,511124108,583.00,03-07-2022,...,Yes,0,1558,21-09-2022,1080,216,8.0,No,0,prateek
11,https://www.youtube.com/watch?v=0HheRYQ9ass,"25,052",The BEST Mockups You Will Find Online!,Satori Graphics - YouTube,Satori,Male,999000,58048539,351.00,8/24/2022,...,Yes,0,70,9/1/2022,1080,918,76.0,No,2,Rahul Singh

4) Some columns are not statistical data but in the form of strings. 
It Is difficult for our model to learn when the data is in form of strings. 
Your task is to encode these strings using proper encoding techniques.

In [ ]:
df.dtypes
# good resources : https://pbpython.com/categorical-encoding.html
# https://www.geeksforgeeks.org/ml-one-hot-encoding-of-datasets-in-python/

# for this question I will be encoding the "Creator gender" and "Language of the video" columns using proper encoding techniques.

# method -1 
temp = pd.get_dummies(df["Creator Gender"])

In [ ]:
print(temp)

     Company  Female  Male
0          0       0     1
1          0       0     1
5          0       0     1
10         0       0     1
11         0       0     1
..       ...     ...   ...
892        0       0     1
893        0       0     1
894        0       1     0
895        0       1     0
896        0       1     0

[563 rows x 3 columns]

In [ ]:
df["Male"] = temp["Male"].to_list() 
df["Female"] = temp["Female"].to_list()
df.head()

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration in Seconds,Date of Video Upload,...,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data,Male,Female
0,https://www.youtube.com/watch?v=_0fUOJ55gis,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,https://www.youtube.com/c/sriharick,srihari ck,Male,40200,7964284,"1,841.00",7/29/2022,...,419,8/6/2022,1080,462,12.0,No,1,Akhil Teja,1,0
1,https://www.youtube.com/watch?v=_70MSLPRfZI,"231,969",Bhoom Baddhal Web Series,https://www.youtube.com/c/ChaibisketTelugu,Chai Bisket,Male,920000,137535681,864.00,5/22/2022,...,189,6/15/2022,1080,251,12.0,Yes,2,Akhil Teja,1,0
5,https://www.youtube.com/watch?v=_HwPGXsklyY,"257,334",HERO - Baananchige Oduva Baara,https://www.youtube.com/c/RishabShettyFilms,Rishab Shetty Films,Male,382000,154898226,361.00,3/24/2021,...,387,4/24/2021,2160,94,14.0,No,0,Akhil Teja,1,0
10,https://www.youtube.com/watch?v=0BBROgyHlFE,"5,599,742",ROUNDER GLUTES: 5 Mistakes Keeping Your Butt Flat,https://www.youtube.com/c/JeremyEthier,Jeremy Ethier,Male,4690000,511124108,583.00,03-07-2022,...,1558,21-09-2022,1080,216,8.0,No,0,prateek,1,0
11,https://www.youtube.com/watch?v=0HheRYQ9ass,"25,052",The BEST Mockups You Will Find Online!,Satori Graphics - YouTube,Satori,Male,999000,58048539,351.00,8/24/2022,...,70,9/1/2022,1080,918,76.0,No,2,Rahul Singh,1,0

In [ ]:
# method 2  
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label = label_encoder.fit_transform(df["Language of the Video"])
df["Language of the Video"] = label
df.head()

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration in Seconds,Date of Video Upload,...,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data,Male,Female
0,https://www.youtube.com/watch?v=_0fUOJ55gis,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,https://www.youtube.com/c/sriharick,srihari ck,Male,40200,7964284,"1,841.00",7/29/2022,...,419,8/6/2022,1080,462,12.0,No,1,Akhil Teja,1,0
1,https://www.youtube.com/watch?v=_70MSLPRfZI,"231,969",Bhoom Baddhal Web Series,https://www.youtube.com/c/ChaibisketTelugu,Chai Bisket,Male,920000,137535681,864.00,5/22/2022,...,189,6/15/2022,1080,251,12.0,Yes,2,Akhil Teja,1,0
5,https://www.youtube.com/watch?v=_HwPGXsklyY,"257,334",HERO - Baananchige Oduva Baara,https://www.youtube.com/c/RishabShettyFilms,Rishab Shetty Films,Male,382000,154898226,361.00,3/24/2021,...,387,4/24/2021,2160,94,14.0,No,0,Akhil Teja,1,0
10,https://www.youtube.com/watch?v=0BBROgyHlFE,"5,599,742",ROUNDER GLUTES: 5 Mistakes Keeping Your Butt Flat,https://www.youtube.com/c/JeremyEthier,Jeremy Ethier,Male,4690000,511124108,583.00,03-07-2022,...,1558,21-09-2022,1080,216,8.0,No,0,prateek,1,0
11,https://www.youtube.com/watch?v=0HheRYQ9ass,"25,052",The BEST Mockups You Will Find Online!,Satori Graphics - YouTube,Satori,Male,999000,58048539,351.00,8/24/2022,...,70,9/1/2022,1080,918,76.0,No,2,Rahul Singh,1,0

Warning: Total number of columns (25) exceeds max_columns (20) limiting to first (20) columns.